version: '3.8'
services: #our three parts is frontend, backend, and databse (mongo)

  #mongo database
  mongo: 
    image: "mongo"
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - data:/data/db

    networks:
      - mern-network


  #this is backend

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports: 
      - "4000:4000"
    
    command: bash -c "node server.js && npm start --legacy-peer-deps"


    image: myapp-backend
    container_name: backend-test

    networks:
      - mern-network

    depends_on:
      - mongo
    

  #frontend
  
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    
    image: myapp-frontend

    container_name: frontend-test

    stdin_open: true

    command: bash -c "npm install --legacy-peer-deps && npm start --legacy-peer-deps"

    networks:
      - mern-network

    depends_on:
      - backend

    ports:
      - "3000:3000"
    

volumes:
  data:
    driver: local

#we use bridge network

networks:
  mern-network:
    driver: bridge
